### ISSUE TITLE
doc-api discrepancy

### ISSUE THREAD

**Issue by ecc-weizhi** [leedongwei/CRIMP#29]
There are discrepancy between doc-api in various branch. The latest version of [doc-api](https://github.com/leedongwei/CRIMP/blob/feature/dongwei/meteor/docs-API.md) has a GET '/api/judge/climber/:climber_id' API which is currently not used by the app. Should we remove it?

**Comment by leedongwei** [comment]
Fixed. Reference copy of docs-API.md is on develop branch.
